/*
documentr - Edit, maintain, and present software documentation on the web.
Copyright (C) 2012 Maik Schreiber

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package de.blizzy.documentr.access;

import java.util.Iterator;
import java.util.Set;

import com.google.common.collect.Sets;

/** Represents a user. */
public class User {
	private String loginName;
	private String password;
	private String email;
	private boolean disabled;
	private Set<OpenId> openIds = Sets.newHashSet();

	/**
	 * Constructs a new user.
	 * 
	 * @param loginName the user's login name
	 * @param password The user's password. This must be an encoded password as generated by the application's
	 *        password encoder.
	 * @param email the user's E-Mail address
	 * @param disabled <code>true</code> if the user's account is disabled, thus preventing login
	 */
	public User(String loginName, String password, String email, boolean disabled) {
		this.loginName = loginName;
		this.password = password;
		this.email = email;
		this.disabled = disabled;
	}

	/** Returns the user's login name. */
	public String getLoginName() {
		return loginName;
	}

	/** Returns the user's encoded password. */
	public String getPassword() {
		return password;
	}
	
	/** Returns the user's E-Mail address. */
	public String getEmail() {
		return email;
	}

	/** Returns whether the user's account is disabled, thus preventing login. */
	public boolean isDisabled() {
		return disabled;
	}
	
	/** Adds an OpenID to this user. */
	public void addOpenId(OpenId openId) {
		openIds.add(openId);
	}

	/** Returns all OpenIDs associated with this user. */
	public Set<OpenId> getOpenIds() {
		return openIds;
	}

	/** Removes an OpenID from this user. Lookup is done using the OpenID's delegate ID. */
	public void removeOpenId(String openId) {
		for (Iterator<OpenId> iter = openIds.iterator(); iter.hasNext();) {
			OpenId id = iter.next();
			if (id.getDelegateId().equals(openId)) {
				iter.remove();
			}
		}
	}
}
